### ISSUE TITLE
Displaying first 100 rows of data

### ISSUE THREAD

**Issue by BaharF** [hpcc-systems/REAL-BI#135]
User should be able to view the first 100 rows of data for ease of use. By viewing the first 100 rows we eliminate the need for user to use watchpage to review the data. 

![wid](https://user-images.githubusercontent.com/26062557/89564304-cbd0cf80-d7ea-11ea-9c23-6cf228125a5a.JPG)

**Comment by chrishuman0923** [comment]
Add data preview to chart editor and as option in chart toolbar. (Both as dialog's).
