### ISSUE TITLE
Deploying RealBI to DataSeer

### ISSUE THREAD

**Issue by BaharF** [hpcc-systems/REAL-BI#166]

**Comment by chrishuman0923** [comment]
Email sent to Adwait and Guru on 11/17/2020.

**Comment by chrishuman0923** [comment]
Email sent to Adwait and Guru on 11/30/2020 to follow-up on the previous email.

**Comment by chrishuman0923** [comment]
Closes due to re-prioritization of issues. Repo's (Real BI/Auth Service) are now public and README's should be sufficient if they wish to clone and use Real BI.
